import os

const readme_path = "./README.md"
const new_line = "\n\n"

const title = "# Advent 2022 👨‍💻$new_line"
const desc = "### This repo is my personal submission of the [Advent Code 2022 calendar](https://adventofcode.com/2022)$new_line"
const sep = "---$new_line"
const table_layout = "| No. | Title | Code |\n| --- | ----- | ---- |\n"
const footer = '> Auto Generated By [this Vlang file](./gen-readme.v)'

fn main() {
	result := os.execute("ls -d */")
	if result.exit_code != 0 || result.output.len == 0 {
		println("ls failed")
		return
	}
	all_days := result.output.split("\n")

	mut readme_file := ""
	readme_file += title
	readme_file += desc
	readme_file += sep
	readme_file += "My [Advent Code 2022](https://adventofcode.com/2022) **submissions**:$new_line"
	readme_file += table_layout

	for i, days in all_days {
		if days.trim_space().len == 0 { continue }
		name := days.trim_right("/")
		if name == "vlang" { continue }

		readme_file += "| ${i+1} | $name | [$days](./$days) |\n"
	}

	readme_file += "\n" + footer

	os.write_file(readme_path, readme_file) or {
		println("failed to write readme file")
		return
	}
}

/* to build run `v -prod -os linux .` */
