name: Generate README.md

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v3

      - name: Run generation
        uses: ./gen-readme

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: The Vlang file
          message: "README Generated!"
